apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: celery-default-stats
  name: celery-default-stats
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "9540"
    port: {{ .Values.celery.stats.port }}
    targetPort: {{ .Values.celery.stats.port }}
  selector:
    io.kompose.service: celery-default-stats
status:
  loadBalancer: {}
