apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  selector:
    matchLabels:
      io.kompose.service: mongodb
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - env:
        - name: MONDODB_LOG_DIR
          value: /dev/null
        - name: MONGODB_DATA_DIR
          value: /data/db
        - name: MONGO_INITDB_DATABASE
          value: {{ .Values.mongodb.initDatabase }}
        image: mongo:latest
        name: mongodb
        ports:
        - containerPort: 27017
        - containerPort: 28017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongodb-claim0
      restartPolicy: Always
      volumes:
      - name: mongodb-claim0
        hostPath: 
          path: {{ .Values.mongodb.nodeDir }}
status: {}
