apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "9090"
    port: {{ .Values.rabbitmq.port }}
    targetPort: {{ .Values.rabbitmq.port }}
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}