apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.8
        name: rabbitmq
        resources: {}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.rabbitmq.port }}
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: {{ .Values.rabbitmq.port }}
          initialDelaySeconds: 20
          periodSeconds: 20
        volumeMounts:
        - mountPath: /etc/rabbitmq/rabbitmq.conf
          name: rabbitmq-claim0
      restartPolicy: Always
      volumes:
      - name: rabbitmq-claim0
        hostPath: 
          path: {{ .Values.rabbitmq.nodeConfigDir }}
status: {}
