apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.20.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: time-worker
  name: time-worker
spec:
  selector:
    matchLabels:
      io.kompose.service: time-worker
  replicas: {{ .Values.timeWorkerReplicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.20.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: time-worker
    spec:
      containers:
      - args:
        - celery
        - worker
        - -E
        - --app=worker.app
        - --pool=gevent
        - --concurrency=20
        - --queues=time
        env:
        - name: CELERY_BROKER_URL
          value: {{ .Values.celery.broker }}
        - name: CELERY_RESULT_BACKEND
          value: rpc
        - name: SCRAP_LOCATION
          value: {{ .Values.scrapLocation}}
        - name: SCRAP_SCHEDULE
          value: "15"
        - name: prometheus_multiproc_dir
          value: /multiprocessing
        image: {{ .Values.baseImage }}
        name: time-worker
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: time-worker-claim0
      restartPolicy: Always
      volumes:
      - name: time-worker-claim0
        hostPath: 
          path: /home/ubuntu/celery_scraper_base/app
status: {}
