global:
  scrape_interval:     10s
  evaluation_interval: 10s
  external_labels:
      monitor: 'lsdp-project'

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
         - targets: ['localhost:9090']
  - job_name: 'webapp'
    scrape_interval: 10s
    static_configs:
      - targets: ['webapp:5000']
  - job_name: 'celery_stats'
    metrics_path: ''
    static_configs:
      - targets: ['celery-default-stats:9540']
